name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make build

    - name: Test
      run: make unittest

    - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: '.'

  build-image:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: published-app
          path: './'

      - name: BuildImage
        run: make buildimage

  
