name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install docker compose
      uses: docker/setup-compose-action@v1

    - name: Build
      run: make build

    - name: Test
      run: |
        make startes
        sleep 20
        make unittest

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: '.'

  publish:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: '.'

      - name: BuildImage
        run: make buildimage

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
        
      - name: Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zhaoyi0113/es-kinesis-firehose-transform-go:latest

  
